"use client";
import { useEffect, useRef, useState } from "react";
import { FFmpeg } from "@ffmpeg/ffmpeg";
import { fetchFile, toBlobURL } from "@ffmpeg/util";
import { ArrowRight, AudioLines, Check, CirclePlay, Clock3, FileAudio, FileVideo, Gauge, Headphones, Image as ImageIcon, Loader2, Menu, Mic2, Music2, Scissors, Settings2, Sparkles, Upload, Video, X, Zap, Download, Play, Pause } from "lucide-react";

type Tool={id:string;label:string;icon:React.ElementType;desc:string};
const tools:Tool[]=[
{id:"mp3",label:"MP3",icon:Music2,desc:"Extract clean audio"},{id:"trim",label:"Trim",icon:Scissors,desc:"Cut any section"},
{id:"speed",label:"Speed",icon:Gauge,desc:"0.25× to 4×"},{id:"compress",label:"Compress",icon:Zap,desc:"Smaller file size"},
{id:"resize",label:"Resize",icon:Settings2,desc:"480p · 720p · 1080p"},{id:"bass",label:"Bass Boost",icon:AudioLines,desc:"Punchier low end"},
{id:"bw",label:"B&W",icon:ImageIcon,desc:"Classic monochrome"},{id:"audio",label:"Audio Mix",icon:Headphones,desc:"Blend media tracks"}];

export default function Home(){
 const inputRef=useRef<HTMLInputElement>(null),audioRef=useRef<HTMLAudioElement>(null),ffmpegRef=useRef<FFmpeg|null>(null);
 const [file,setFile]=useState<File|null>(null),[url,setUrl]=useState(""),[result,setResult]=useState("");
 const [tool,setTool]=useState("mp3"),[speed,setSpeed]=useState(1),[duration,setDuration]=useState(""),[mobileOpen,setMobileOpen]=useState(false);
 const [status,setStatus]=useState<"idle"|"ready"|"processing"|"done">("idle"),[progress,setProgress]=useState(0),[playing,setPlaying]=useState(false),[error,setError]=useState("");
 useEffect(()=>()=>{if(url)URL.revokeObjectURL(url);if(result)URL.revokeObjectURL(result)},[url,result]);
 const pick=(f?:File)=>{if(!f||(!f.type.startsWith("video/")&&!f.type.startsWith("audio/")))return;if(url)URL.revokeObjectURL(url);if(result)URL.revokeObjectURL(result);setFile(f);setUrl(URL.createObjectURL(f));setResult("");setProgress(0);setError("");setStatus("ready")};
 const reset=()=>{if(url)URL.revokeObjectURL(url);if(result)URL.revokeObjectURL(result);setFile(null);setUrl("");setResult("");setStatus("idle");setProgress(0);setError("")};
 const convert=async()=>{if(!file||status==="processing")return;setError("");setStatus("processing");setProgress(3);try{let ffmpeg=ffmpegRef.current;if(!ffmpeg){ffmpeg=new FFmpeg();ffmpeg.on("progress",({progress})=>setProgress(Math.max(5,Math.min(99,Math.round(progress*100)))));const baseURL="https://cdn.jsdelivr.net/npm/@ffmpeg/core@0.12.10/dist/umd";await ffmpeg.load({coreURL:await toBlobURL(baseURL+"/ffmpeg-core.js","text/javascript"),wasmURL:await toBlobURL(baseURL+"/ffmpeg-core.wasm","application/wasm")});ffmpegRef.current=ffmpeg}setProgress(8);const inputName="input"+(file.name.includes(".")?"."+file.name.split(".").pop():"");await ffmpeg.writeFile(inputName,await fetchFile(file));let args:string[]=[];let output="output.mp3";if(tool==="mp3"){args=["-i",inputName,"-vn","-codec:a","libmp3lame","-q:a","2",output]}else if(tool==="speed"){const atempo=speed;let filters:string[]=[];let remaining=atempo;while(remaining<0.5){filters.push("atempo=0.5");remaining*=2}while(remaining>2){filters.push("atempo=2");remaining/=2}filters.push("atempo="+remaining);output="output."+((file.type.startsWith("audio/"))?"mp3":"mp4");args=file.type.startsWith("audio/")?["-i",inputName,"-af",filters.join(","),"-codec:a","libmp3lame","-q:a","2",output]:["-i",inputName,"-vf","setpts="+(1/speed)+"*PTS","-af",filters.join(","),output]}else if(tool==="compress"){output=file.type.startsWith("audio/")?"output.mp3":"output.mp4";args=file.type.startsWith("audio/")?["-i",inputName,"-b:a","128k",output]:["-i",inputName,"-c:v","libx264","-crf","30","-preset","veryfast","-c:a","aac","-b:a","128k",output]}else if(tool==="bw"){output="output.mp4";args=["-i",inputName,"-vf","format=gray","-c:a","copy",output]}else if(tool==="resize"){output="output.mp4";args=["-i",inputName,"-vf","scale=-2:720","-c:v","libx264","-preset","veryfast","-c:a","aac",output]}else if(tool==="trim"){output="output."+((file.type.startsWith("audio/"))?"mp3":"mp4");args=["-i",inputName,"-t","30",output]}else if(tool==="bass"){output="output.mp3";args=["-i",inputName,"-af","bass=g=8","-codec:a","libmp3lame","-q:a","2",output]}else{output="output.mp4";args=["-i",inputName,"-c:v","libx264","-c:a","aac","-preset","veryfast",output]}await ffmpeg.exec(args);setProgress(99);const data=await ffmpeg.readFile(output);const mime=output.endsWith(".mp3")?"audio/mpeg":"video/mp4";const blobBytes=typeof data==="string"?new TextEncoder().encode(data):new Uint8Array(data);const u=URL.createObjectURL(new Blob([blobBytes],{type:mime}));setResult(u);setProgress(100);setStatus("done");}catch(e){setProgress(0);setStatus("ready");setError(e instanceof Error?e.message:"Conversion failed")}};
 const toggle=()=>{if(!audioRef.current)return;if(audioRef.current.paused){audioRef.current.play();setPlaying(true)}else{audioRef.current.pause();setPlaying(false)}};
 return <main className="min-h-screen overflow-hidden">
 <nav className="nav"><div className="brand"><span className="brand-mark"><Sparkles size={17}/></span><span>Media<span className="muted">Flow</span></span></div><div className="nav-links"><a href="#tools">Tools</a><a href="#how">How it works</a><a href="#about">About</a></div><button className="mobile-menu" onClick={()=>setMobileOpen(!mobileOpen)}><Menu size={20}/></button><a className="nav-cta" href="#converter">Start converting <ArrowRight size={15}/></a></nav>{mobileOpen&&<div className="mobile-links"><a href="#tools">Tools</a><a href="#how">How it works</a><a href="#about">About</a></div>}
 <section className="hero"><div className="hero-glow one"/><div className="hero-glow two"/><div className="eyebrow"><span className="dot"/> NO LOGIN • FREE TO USE</div><h1>Turn your media into<br/><span>something better.</span></h1><p className="hero-copy">Upload a song or video, listen instantly, watch conversion progress and download the finished file.</p><div className="hero-actions"><a href="#converter" className="primary">Upload media <Upload size={17}/></a><a href="#tools" className="secondary">Explore tools <ArrowRight size={16}/></a></div><div className="trust"><span><Check size={14}/> No login</span><span><Check size={14}/> Free</span><span><Check size={14}/> Mobile friendly</span></div></section>
 <section id="converter" className="workspace-wrap"><div className="workspace"><div className="workspace-head"><div><div className="section-kicker">CONVERTER</div><h2>Drop your media here</h2></div><span className="format-pill">VIDEO / AUDIO</span></div>
 {!file?<div className="dropzone" onClick={()=>inputRef.current?.click()} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();pick(e.dataTransfer.files[0])}}><input ref={inputRef} hidden type="file" accept="video/*,audio/*" onChange={e=>pick(e.target.files?.[0])}/><div className="upload-icon"><Upload size={26}/></div><h3>Drag & drop your file</h3><p>or click to browse from your device</p><div className="file-types"><span><FileVideo size={14}/> MP4</span><span><FileAudio size={14}/> MP3</span><span>WEBM</span><span>MOV</span><span>WAV</span></div></div>
 :<div className="editor"><div className="file-card"><div className="file-icon">{file.type.startsWith("video")?<Video size={21}/>:<Mic2 size={21}/>}</div><div className="file-info"><b>{file.name}</b><span>{(file.size/1024/1024).toFixed(2)} MB</span></div><button className="icon-btn" onClick={reset}><X size={17}/></button></div>
 <div className="preview-card">{file.type.startsWith("video/")?<video className="media-preview" src={url} controls/>:<><div className="audio-art"><Music2 size={30}/></div><audio ref={audioRef} src={url} controls onPlay={()=>setPlaying(true)} onPause={()=>setPlaying(false)} onEnded={()=>setPlaying(false)}/></>}<button className="preview-play" onClick={toggle}>{playing?<Pause size={15}/>:<Play size={15}/>} {playing?"Playing":"Listen"}</button></div>
 <div className="tool-grid">{tools.map(t=>{const I=t.icon;return <button key={t.id} className={"tool "+(tool===t.id?"active":"")} onClick={()=>setTool(t.id)}><I size={18}/><span>{t.label}</span><small>{t.desc}</small></button>})}</div>
 <div className="controls">{tool==="speed"&&<><label>Speed <b>{speed}×</b></label><input className="range" type="range" min=".25" max="4" step=".25" value={speed} onChange={e=>setSpeed(+e.target.value)}/><div className="range-labels"><span>0.25×</span><span>1×</span><span>4×</span></div><label>Target duration</label><input className="text-input" placeholder="e.g. 03:00" value={duration} onChange={e=>setDuration(e.target.value)}/></>}{tool==="trim"&&<><label>Cut range</label><div className="dual-input"><input className="text-input" placeholder="Start 00:00"/><input className="text-input" placeholder="End 00:30"/></div></>}{tool==="resize"&&<><label>Output quality</label><div className="option-row">{["480p","720p","1080p"].map(x=><button className="option" key={x}>{x}</button>)}</div></>}{tool==="compress"&&<><label>Compression level</label><div className="option-row">{["Light","Balanced","Maximum"].map(x=><button className="option" key={x}>{x}</button>)}</div></>}{!["speed","trim","resize","compress"].includes(tool)&&<div className="simple-control"><CirclePlay size={17}/><span>Ready to apply <b>{tools.find(x=>x.id===tool)?.label}</b></span></div>}</div>
 {status==="processing"&&<div className="progress-box"><div className="progress-top"><span>Converting {tools.find(x=>x.id===tool)?.label}…</span><b>{progress}%</b></div><div className="progress-track"><div className="progress-fill" style={{width:progress+"%"}}/></div><small>Processing… please keep this tab open.</small></div>}
 {status==="done"&&result&&<div className="result-card"><div><div className="result-badge"><Check size={14}/> Conversion complete</div><b>Your file is ready</b><span>Download the finished media below.</span></div><a className="download-btn" href={result} download={"mediaflow-"+file.name}><Download size={17}/> Download</a></div>}
 {error&&<div className="error-box">{error}</div>}
 <button className="convert-btn" onClick={convert} disabled={status==="processing"}>{status==="processing"?<><Loader2 className="spin" size={18}/> Converting…</>:status==="done"?<><Check size={18}/> Converted</>:<>Convert media <ArrowRight size={18}/></>}</button><p className="workspace-note"><Clock3 size={13}/> No login required · Free to use · Conversion runs in your browser.</p></div>}</div></section>
 <section id="tools" className="section"><div className="section-kicker">EVERYDAY TOOLS</div><h2>Everything you need,<br/><span>nothing you don’t.</span></h2><div className="feature-grid">{tools.map(t=>{const I=t.icon;return <div className="feature" key={t.id}><div className="feature-icon"><I size={19}/></div><h3>{t.label}</h3><p>{t.desc}</p></div>})}</div></section>
 <section id="how" className="how section"><div><div className="section-kicker">HOW IT WORKS</div><h2>Three steps.<br/><span>Zero clutter.</span></h2></div><div className="steps"><div><b>01</b><h3>Upload & listen</h3><p>Drop your song or video and preview it immediately.</p></div><div><b>02</b><h3>Choose & convert</h3><p>Pick a tool and watch the progress bar.</p></div><div><b>03</b><h3>Download</h3><p>When processing finishes, download your result.</p></div></div></section>
 <footer id="about"><div className="brand"><span className="brand-mark"><Sparkles size={15}/></span>MediaFlow</div><span>NO LOGIN • FREE TO USE</span></footer></main>
}